In [1]:
import numpy as np

# Starting Numbers
#x0 ─┬──────────────┐
#    │              │
#    │              ▼
#    │        ┌──────────┐
#    │        │ Hidden   │
#    │        │ Neuron 0 │──┐
#    │        └──────────┘  │
#    │                      │
#    │                      ▼
#    │                    ┌───────┐
#    │                    │       │
#    │                    │ Output│──► y ─► L
#    │                    │Neuron │
#    │                    │       │
#    │                    └───────┘
#    │                      ▲
#    │                      │
#    │        ┌──────────┐  │
#    │        │ Hidden   │──┘
#    │        │ Neuron 1 │
#    │        └──────────┘
#    │
#x1 ─┴──────────────────────


x0 = 1.2
x1 = -0.7
x = np.array([[x0, x1]])
w00 = 0.5
w10 = 1.0
w1 = np.array([[w00, w10]])
w11 = 0.9
w01 = -0.4
w2 = np.array([[w01, w11]])
w_1 = np.array([[0.5, -0.4], [1.0, 0.9]], dtype=float)
b10 = 0.2
b11 = 1.3
b1 = np.array([[b10, b11]])
v0 = 1.4
v1 = -0.8
w_2 = np.array([[v0, v1]]).T
b2 = 0.05
y_true = 0.7
w_1

array([[ 0.5, -0.4],
       [ 1. ,  0.9]])

In [2]:
z1 = x0 * w00 + x1 * w10 + b10
z1
print(z1)
z1 == np.dot(x, w1.T) + b10

0.10000000000000003


array([[ True]])

In [3]:
z2 = x0 * w01 + x1 * w11 + b11
z2
print(z2)
z2 == np.dot(x, w2.T) + b11

0.19000000000000017


array([[ True]])

In [4]:
z = np.dot(x, w_1) + b1
z

array([[0.1 , 0.19]])

In [5]:
h0 = z1 if z1 > 0 else 0
h0

0.10000000000000003

In [6]:
h1 = z2 if z2 > 0 else 0
h1

0.19000000000000017

In [7]:
h = np.array([[h0, h1]])
h

array([[0.1 , 0.19]])

In [8]:
y = h0 * v0 + h1 * v1 + b2
y
print(y)
y == np.dot(z, w_2) + b2

0.03799999999999991


array([[ True]])

In [9]:
L = (1/2)*(y - y_true) ** 2

In [10]:
dl_dy = y - y_true
dy_db2 = 1
dy_dv0 = h0
dy_dv1 = h1
dy_dh0 = v0
dy_dh1 = v1

In [11]:
dl_db2 = dl_dy * dy_db2
dl_db2

-0.662

In [12]:
dl_dv0 = dl_dy * dy_dv0
dl_dv0

-0.06620000000000002

In [13]:
dl_dv1 = dl_dy * dy_dv1
dl_dv1

-0.12578000000000011

In [14]:
dl_dh0 = dl_dy * dy_dh0
dl_dh0

-0.9268

In [15]:
dl_dh1 = dl_dy * dy_dh1
dl_dh1

0.5296000000000001

In [16]:
dz1_dx0 = w00

In [17]:
dz1_dx1 = w10

In [18]:
dz1_dw00 = x0

In [19]:
dz1_dw10 = x1

In [20]:
dz1_db1 = 1

In [21]:
dy_dz1 = dy_dh0

In [22]:
dl_dw00 = dl_dy * dy_dz1 * dz1_dw00
dl_dw00

-1.1121599999999998

In [23]:
dl_dw10 = dl_dy * dy_dz1 * dz1_dw10
dl_dw10

0.6487599999999999

In [24]:
dl_dx0 = dl_dy * dy_dz1 * dz1_dx0
dl_dx0

-0.4634

In [25]:
dl_dx1 = dl_dy * dy_dz1 * dz1_dx1
dl_dx1

-0.9268

In [26]:
dl_db1 = dl_dy * dy_dz1 * dz1_db1
dl_db1

-0.9268

In [32]:
dl_dw2 = np.dot(dl_dy, h.T)
dl_dw2

array([[-0.0662 ],
       [-0.12578]])

In [30]:
dl_dh = np.dot(dl_dy, w2.T)
dl_dh

array([[ 0.2648],
       [-0.5958]])